ActsAsRelation.setup do |config|

  # Define whether derived models should automatically join with their superclass. This would
  # default to false in Rails >= 3.x because includes will automatically figure out the right
  # semantics to use. In Rails >= 4.1 this is also false because the Rails 3.x behaviour is
  # deprecated, and on occasion with duplicate column names (e.g. when using the Paranoia gem)
  # invalid join statements will be generated by ActiveRecord.
  # config.auto_join = false

end
